CREATE TABLE USERS (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "USERNAME" TEXT,
    "EMAIL" TEXT,
    "PASSWORD" TEXT,
    "CREDIT_CARD" TEXT
);
CREATE TABLE POSTS (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "TITLE" TEXT,
    "PRICE" TEXT,
    "CONTENT" TEXT
);

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, CREDIT_CARD)
VALUES ('foo', '19841984', 'foo@bar.baz', '2564-1532-2222-5684');
